<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access Token' => 'Token de acesso',
    'Admin' => 'Administrador',
    'Aproveitamento' => 'Aproveitamento',
    'Aproveitamento Equipe' => 'Aproveitamento da Equipe',
    'Are you sure you want to delete this item?' => 'Você tem certeza que quer deletar esse item?',
    'Auth Key' => 'Chave de acesso',
    'Cadastrar-se' => 'Cadastrar-se',
    'Campeonato Idcampeonato' => 'Id do Campeonato',
    'Campeonatos' => 'Campeonatos',
    'Confirmar Senha' => 'Confirmar Senha',
    'Create Campeonato' => 'Criar Campeonato',
    'Create Equipe' => 'Criar Equipe',
    'Create Equipe Grupo' => 'Criar Equipe Grupo',
    'Create Grupo' => 'Criar Grupo',
    'Create Jogador' => 'Criar Jogador',
    'Create Jogo' => 'Criar Jogo',
    'Create Usuario' => 'Criar Usuario',
    'Delete' => 'Apagar',
    'Derrota' => 'Derrota',
    'Derrota Equipe' => 'Derrotas da equipe',
    'Email' => 'E-mail',
    'Empate' => 'Empate',
    'Empate Equipe' => 'Empates da equipe',
    'Equipe' => 'Equipe',
    'Equipe A' => 'Equipe A',
    'Equipe B' => 'Equipe B',
    'Equipe Grupos' => 'Equipe Grupos',
    'Equipe Nome' => 'Nome da equipe',
    'Equipes' => 'Equipes',
    'Formato' => 'Formato',
    'Groups will be divisible by Temas number' => 'Número de grupos tem que ser divisivel pelo número de Equipes',
    'Groups will be less than Teams' => 'Número de grupos tem que ser menor que o número de Equipes',
    'Grupo Idgrupo' => 'Id do grupo',
    'Grupos' => 'Grupos',
    'Id  Jogador' => 'Id do Jogador',
    'Idcampeonato' => 'Id do Campeonato',
    'Idequipe' => 'Id da Equipe',
    'Idgrupo' => 'Id do grupo',
    'Idjogo' => 'Id do Jogo',
    'Idusuario' => 'Id do Usuario',
    'Jogador' => 'Jogador',
    'Jogadors' => 'Jogadores',
    'Jogos' => 'Jogos',
    'Modalidade' => 'Modalidade',
    'Nome' => 'Nome',
    'Pontuacao A' => 'Pontuação time A',
    'Pontuacao B' => 'Pontuação time B',
    'Pontuacao Jogador' => 'Pontuação Jogador',
    'Qtd Equipe' => 'Número de Equipes',
    'Qtd Equipe Grupo' => 'Número de equipes por grupo',
    'Qtd Grupo' => 'Número de grupos',
    'Reset' => 'Reinicar',
    'Saldo' => 'Saldo',
    'Saldo Equipe' => 'Saldo da equipe',
    'Save' => 'Salvar',
    'Search' => 'Procurar',
    'Senha' => 'Senha',
    'The requested page does not exist.' => 'A pagina não existe',
    'Update' => 'Atualizar',
    'Update Campeonato: mode' => 'Atualizar Campeonato: modo',
    'Update Equipe Grupo: mode' => 'Atualizar Equipe Grupo: modo',
    'Update Equipe: mode' => 'Atualizar Equipe: modo',
    'Update Grupo: mode' => 'Atualizar Grupo: modo',
    'Update Jogador: mode' => 'Atualizar Jogador: modo',
    'Update Jogo: mode' => 'Atualizar jogo: modo',
    'User' => 'Usuario',
    'Usuario' => 'Usuario',
    'Usuario Idusuario' => 'Id do Usuario',
    'Usuarios' => 'Usuarios',
    'Vitoria' => 'Vitoria',
    'Vitoria Equipe' => 'Vitorias da Equipe',
    '{user}' => '',
    'Settings' => 'Configurações',
];
